In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import time
import numpy as np

import encode
import quanqual
import EDA
import EDA1

import Capstone1_model

from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
st_habits = pd.read_csv('student_habits.csv')         # raw data

st_habits1 = st_habits.copy()

st_habits1

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,Female,2.6,0.5,1.6,No,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
996,S1996,17,Female,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
997,S1997,20,Male,3.0,2.6,1.3,No,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
998,S1998,24,Male,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
999,S1999,19,Female,4.3,2.9,1.9,No,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [3]:
st_habits1 = encode.data_rename(st_habits1)

In [4]:
st_habits1 = encode.data_encoding(st_habits1)

In [5]:
st_habits1

,age,study_hrs,part_time_job,media_hrs,att_percent,sleep_hrs,diet_quality,exercise_fq,internet_quality,mental_health_rating,extracurricular,exam_score,gender_Female,gender_Male,gender_Other,par_edu_Bachelor,par_edu_High School,par_edu_Master,par_edu_Unknown
0,23,0.0,0,2.3,85.0,8.0,1,6,1,8,1,56.2,1,0,0,0,0,1,0
1,20,6.9,0,5.1,97.3,4.6,2,6,1,8,0,100.0,1,0,0,0,1,0,0
2,21,1.4,0,4.4,94.8,8.0,0,1,0,1,0,34.3,0,1,0,0,1,0,0
3,23,1.0,0,4.9,71.0,9.2,0,4,2,1,1,26.8,1,0,0,0,0,1,0
4,19,5.0,0,4.9,90.9,4.9,1,3,2,1,0,66.4,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,21,2.6,0,2.1,77.0,7.5,1,2,2,6,1,76.1,1,0,0,0,1,0,0
996,17,2.9,1,3.4,86.0,6.8,0,1,1,6,1,65.9,1,0,0,0,1,0,0
997,20,3.0,0,3.9,61.9,6.5,2,5,2,9,1,64.4,0,1,0,1,0,0,0
998,24,5.4,1,5.2,100.0,7.6,1,0,1,1,0,69.7,0,1,0,1,0,0,0
999,19,4.3,0,4.8,89.4,7.1,2,2,1,8,0,74.9,1,0,0,1,0,0,0

In [6]:
st_habits1['mental_health_warning'] = (st_habits1['mental_health_rating'] >= 3).astype(int)

### Defining the target variable : Mental health warning : Rating<=3 high risk 

st_habits1

,age,study_hrs,part_time_job,media_hrs,att_percent,sleep_hrs,diet_quality,exercise_fq,internet_quality,mental_health_rating,extracurricular,exam_score,gender_Female,gender_Male,gender_Other,par_edu_Bachelor,par_edu_High School,par_edu_Master,par_edu_Unknown,mental_health_warning
0,23,0.0,0,2.3,85.0,8.0,1,6,1,8,1,56.2,1,0,0,0,0,1,0,1
1,20,6.9,0,5.1,97.3,4.6,2,6,1,8,0,100.0,1,0,0,0,1,0,0,1
2,21,1.4,0,4.4,94.8,8.0,0,1,0,1,0,34.3,0,1,0,0,1,0,0,0
3,23,1.0,0,4.9,71.0,9.2,0,4,2,1,1,26.8,1,0,0,0,0,1,0,0
4,19,5.0,0,4.9,90.9,4.9,1,3,2,1,0,66.4,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,21,2.6,0,2.1,77.0,7.5,1,2,2,6,1,76.1,1,0,0,0,1,0,0,1
996,17,2.9,1,3.4,86.0,6.8,0,1,1,6,1,65.9,1,0,0,0,1,0,0,1
997,20,3.0,0,3.9,61.9,6.5,2,5,2,9,1,64.4,0,1,0,1,0,0,0,1
998,24,5.4,1,5.2,100.0,7.6,1,0,1,1,0,69.7,0,1,0,1,0,0,0,0
999,19,4.3,0,4.8,89.4,7.1,2,2,1,8,0,74.9,1,0,0,1,0,0,0,1

In [7]:

indep_X = st_habits1.drop(columns=['mental_health_rating','mental_health_warning'])

dep_Y = st_habits1['mental_health_warning']

In [8]:
indep_X

,age,study_hrs,part_time_job,media_hrs,att_percent,sleep_hrs,diet_quality,exercise_fq,internet_quality,extracurricular,exam_score,gender_Female,gender_Male,gender_Other,par_edu_Bachelor,par_edu_High School,par_edu_Master,par_edu_Unknown
0,23,0.0,0,2.3,85.0,8.0,1,6,1,1,56.2,1,0,0,0,0,1,0
1,20,6.9,0,5.1,97.3,4.6,2,6,1,0,100.0,1,0,0,0,1,0,0
2,21,1.4,0,4.4,94.8,8.0,0,1,0,0,34.3,0,1,0,0,1,0,0
3,23,1.0,0,4.9,71.0,9.2,0,4,2,1,26.8,1,0,0,0,0,1,0
4,19,5.0,0,4.9,90.9,4.9,1,3,2,0,66.4,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,21,2.6,0,2.1,77.0,7.5,1,2,2,1,76.1,1,0,0,0,1,0,0
996,17,2.9,1,3.4,86.0,6.8,0,1,1,1,65.9,1,0,0,0,1,0,0
997,20,3.0,0,3.9,61.9,6.5,2,5,2,1,64.4,0,1,0,1,0,0,0
998,24,5.4,1,5.2,100.0,7.6,1,0,1,0,69.7,0,1,0,1,0,0,0
999,19,4.3,0,4.8,89.4,7.1,2,2,1,0,74.9,1,0,0,1,0,0,0

In [9]:
dep_Y

0      1
1      1
2      0
3      0
4      0
      ..
995    1
996    1
997    1
998    0
999    1
Name: mental_health_warning, Length: 1000, dtype: int64

In [10]:
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

kbest=Capstone1_model.selectkbest(indep_X,dep_Y,4) 

classifier = Capstone1_model.split_scalar(indep_X,dep_Y)
Capstone1_model.split_scalar(indep_X,dep_Y)

(array([[ 0.22548596,  2.17445014, -0.52695648, ..., -0.78509828,
         -0.42992339, -0.32336595],
        [-0.20703187,  1.41630571, -0.52695648, ...,  1.27372588,
         -0.42992339, -0.32336595],
        [-0.63954969, -1.27166094, -0.52695648, ..., -0.78509828,
         -0.42992339, -0.32336595],
        ...,
        [ 1.09052161,  1.34738348,  1.89768991, ...,  1.27372588,
         -0.42992339, -0.32336595],
        [ 0.65800378, -0.5135165 , -0.52695648, ...,  1.27372588,
         -0.42992339, -0.32336595],
        [-1.50458534,  0.1067835 , -0.52695648, ..., -0.78509828,
         -0.42992339, -0.32336595]], shape=(750, 18)),
 array([[-0.20703187,  0.17570572, -0.52695648, ...,  1.27372588,
         -0.42992339, -0.32336595],
        [ 1.09052161, -1.34058316, -0.52695648, ...,  1.27372588,
         -0.42992339, -0.32336595],
        [ 0.22548596,  1.27846126, -0.52695648, ...,  1.27372588,
         -0.42992339, -0.32336595],
        ...,
        [ 0.22548596, -1.4784276 , -0.52695648, ...,  1.27372588,
         -0.42992339, -0.32336595],
        [-1.50458534,  2.10552792, -0.52695648, ...,  1.27372588,
         -0.42992339, -0.32336595],
        [-0.20703187, -0.72028316, -0.52695648, ..., -0.78509828,
         -0.42992339, -0.32336595]], shape=(250, 18)),
 253    0
 667    1
 85     1
 969    1
 75     1
       ..
 835    1
 192    1
 629    0
 559    1
 684    1
 Name: mental_health_warning, Length: 750, dtype: int64,
 993    1
 859    0
 298    1
 553    0
 672    1
       ..
 462    1
 356    1
 2      0
 478    1
 695    1
 Name: mental_health_warning, Length: 250, dtype: int64)

In [11]:
X_train, X_test, y_train, y_test = Capstone1_model.split_scalar(kbest,dep_Y)   


classifier ,Accuracy,report,cm = Capstone1_model.logistic(X_train,y_train,X_test,y_test)
Capstone1_model.logistic(X_train,y_train,X_test,y_test)
acclog.append(Accuracy)

classifier ,Accuracy,report,cm  = Capstone1_model.svm_linear(X_train,y_train,X_test,y_test)
Capstone1_model.svm_linear(X_train,y_train,X_test,y_test)
accsvml.append(Accuracy)

classifier ,Accuracy,report,cm  = Capstone1_model.svm_NL(X_train, y_train,X_test,y_test)
Capstone1_model.svm_NL(X_train, y_train,X_test,y_test)
accsvmnl.append(Accuracy)

classifier ,Accuracy,report,cm = Capstone1_model.Navie(X_train,y_train,X_test,y_test)
Capstone1_model.Navie(X_train,y_train,X_test,y_test)
accnav.append(Accuracy)

classifier ,Accuracy,report,cm  = Capstone1_model.knn(X_train,y_train,X_test,y_test)
Capstone1_model.knn(X_train,y_train,X_test,y_test)
accknn.append(Accuracy)

classifier ,Accuracy,report,cm = Capstone1_model.Decision(X_train,y_train,X_test,y_test)
Capstone1_model.Decision(X_train,y_train,X_test,y_test)
accdes.append(Accuracy)

classifier ,Accuracy,report,cm  = Capstone1_model.random(X_train,y_train,X_test,y_test)
Capstone1_model.random(X_train,y_train,X_test,y_test)
accrf.append(Accuracy)


result = Capstone1_model.selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

/opt/anaconda3/envs/AIML/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/AIML/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/AIML/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/AIML/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/AIML/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/AIML/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/AIML/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/AIML/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/AIML/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/AIML/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/AIML/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/AIML/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/vijaybala/RadhiJupyterNotebooks/AIML/Capstone Project 1/Feature Selection and Model4/Capstone1_model.py:102: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Logistic'][idex]=acclog[number]
/Users/vijaybala/RadhiJupyterNotebooks/AIML/Capstone Project 1/Feature Selection and Model4/Capstone1_model.py:103: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['SVMl'][idex]=accsvml[number]
/Users/vijaybala/RadhiJupyterNotebooks/AIML/Capstone Project 1/Feature Selection and Model4/Capstone1_model.py:104: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['SVMnl'][idex]=accsvmnl[number]
/Users/vijaybala/RadhiJupyterNotebooks/AIML/Capstone Project 1/Feature Selection and Model4/Capstone1_model.py:105: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['KNN'][idex]=accknn[number]
/Users/vijaybala/RadhiJupyterNotebooks/AIML/Capstone Project 1/Feature Selection and Model4/Capstone1_model.py:106: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Navie'][idex]=accnav[number]
/Users/vijaybala/RadhiJupyterNotebooks/AIML/Capstone Project 1/Feature Selection and Model4/Capstone1_model.py:107: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Decision'][idex]=accdes[number]
/Users/vijaybala/RadhiJupyterNotebooks/AIML/Capstone Project 1/Feature Selection and Model4/Capstone1_model.py:108: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Random'][idex]=accrf[number]

In [12]:
result

          Logistic   SVMl  SVMnl   KNN  Navie Decision Random
ChiSquare    0.812  0.816  0.816  0.78  0.764    0.688  0.724

In [14]:
selector = SelectKBest(score_func=chi2, k=4)
selector.fit(indep_X, dep_Y)
selected_cols = indep_X.columns[selector.get_support()]
print(selected_cols)

Index(['age', 'extracurricular', 'exam_score', 'par_edu_Master'], dtype='object')